### ISSUE TITLE
Update GL2 from ioq3 GL2

### ISSUE THREAD

**Issue by DT85** [DT85/OpenDF2#5]
This may include a dumping of any changes Xycaleth has made due to the large differences.

- [ ] UsingVAO instead of IBO & VBO
- [ ] OpenGL Direct State Access
- [x] Shadow mapping (cg_shadows 4) is partially working, just shows a blob for the moment
- [x] PBR
- [ ] Code cleanup

**Comment by SomaZ** [comment]
Xycaleth's changes are very nice though. For example the render stages. It would be nice to have an overview on the relevant changes of ioq3. Maybe I can include relevant changes from ioq3, but I really have no time to search for every little optimization.

**Comment by DT85** [comment]
This is what I know so far:

- changed from VBO & IBO to VAO
- OpenGL Direct State Access
- Shadow mapping (cg_shadows 4) is partially working, just shows a blob for the moment

**Comment by DT85** [comment]
Somaz is handling renderer stuff.
