### ISSUE TITLE
Burn marks on Ghoul2 models aren't showing properly

### ISSUE THREAD

**Issue by DT85** [DT85/OpenDF2#7]
The BSP burn marks show fine, just the Ghoul2 one "gfx/damage/burnmark1"

https://dl.dropboxusercontent.com/u/16660487/Burn%20Marks.jpg

**Comment by SomaZ** [comment]
To be honest, I always hated them. Always bugged me, that some guy with serious burn marks can still stand, shoot and so on.

**Comment by DT85** [comment]
True, but we still need them. The ones that show on the walls look fine though.

**Comment by DT85** [comment]
Not doing this. Going to turn off g2 burn marks instead via the cvar.
