### ISSUE TITLE
Shader Definitions

### ISSUE THREAD

**Issue by DT85** [DT85/OpenDF2#8]
•Add some definitions for roughness shininess smoothness and gloss to the specularmap definition in the old shaders
•remove cvar r_glossType

**Comment by SomaZ** [comment]
Actually I don't want to add support for gloss, shininess and smoothness anymore. I fixed the pipeline on roughness and removed r_glossType. You can close the issue, when you are fine with it.

**Comment by DT85** [comment]
Somaz is handling renderer stuff.
